name: Auto Update README

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Python Script
      run: |
        python util/update-readme.py "${{ github.event.pull_request.title }}" "${{ github.event.pull_request.body}}" "${{ github.event.pull_request.merged_at }}" "${{ github.event.pull_request.user.login }}"
    - name: Commit Changes
      run: |
        git add .
        git config --local user.email "tjrdud6412@naver.com"
        git config --local user.name "c9u11"
        git commit -m "📝 EDIT INDEX"
    - name: Push Commits
      run: |
        git push
